apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: room3-capstone2-cluster4
    app.kubernetes.io/instance: room3-capstone2-cluster4-instance
    app.kubernetes.io/version: "1.0.0"
    app.kubernetes.io/component: backend
    app.kubernetes.io/managed-by: kubectl
  name: room3-capstone2-cluster4
spec:
  selector:
    app: room3-capstone2-cluster4
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: <Port>